package prometheus

// MetricKey 메트릭 키
type MetricKey string

const (
	ContainerCpu                          = MetricKey("container_cpu")
	ContainerFileSystem                   = MetricKey("container_file_system")
	ContainerMemory                       = MetricKey("container_memory")
	ContainerNetworkIn                    = MetricKey("container_network_in")
	ContainerNetworkOut                   = MetricKey("container_network_out")
	NodeCpu                               = MetricKey("node_cpu")
	NodeFileSystem                        = MetricKey("node_file_system")
	NodeMemory                            = MetricKey("node_memory")
	NodeNetworkIn                         = MetricKey("node_network_in")
	NodeNetworkOut                        = MetricKey("node_network_out")
	NumberOfDeployment                    = MetricKey("number_of_deployment")
	NumberOfIngress                       = MetricKey("number_of_ingress")
	NumberOfPod                           = MetricKey("number_of_pod")
	NumberOfNamespace                     = MetricKey("number_of_namespace")
	NumberOfService                       = MetricKey("number_of_service")
	NumberOfStatefulSet                   = MetricKey("number_of_statefulset")
	NumberOfVolume                        = MetricKey("number_of_volume")
	TopNodeCpuByInstance                  = MetricKey("top_node_cpu_by_instance")
	TopNodeFileSystemByInstance           = MetricKey("top_node_file_system_by_instance")
	TopNodeMemoryByInstance               = MetricKey("top_node_memory_by_instance")
	TopNodeNetworkInByInstance            = MetricKey("top_node_network_in_by_instance")
	TopNodeNetworkOutByInstance           = MetricKey("top_node_network_out_by_instance")
	TopCountPodByNode                     = MetricKey("top_count_pod_by_node")
	Top5ContainerCpuByNamespace           = MetricKey("top5_container_cpu_by_namespace")
	Top5ContainerCpuByPod                 = MetricKey("top5_container_cpu_by_pod")
	Top5ContainerFileSystemByNamespace    = MetricKey("top5_container_file_system_by_namespace")
	Top5ContainerFileSystemByPod          = MetricKey("top5_container_file_system_by_pod")
	Top5ContainerMemoryByNamespace        = MetricKey("top5_container_memory_by_namespace")
	Top5ContainerMemoryByPod              = MetricKey("top5_container_memory_by_pod")
	Top5ContainerNetworkInByNamespace     = MetricKey("top5_container_network_in_by_namespace")
	Top5ContainerNetworkInByPod           = MetricKey("top5_container_network_in_by_pod")
	Top5ContainerNetworkOutByNamespace    = MetricKey("top5_container_network_out_by_namespace")
	Top5ContainerNetworkOutByPod          = MetricKey("top5_container_network_out_by_pod")
	Top5CountPodByNamespace               = MetricKey("top5_count_pod_by_namespace")
	QuotaCpuLimit                         = MetricKey("quota_cpu_limit")
	QuotaCpuRequest                       = MetricKey("quota_cpu_request")
	QuotaMemoryLimit                      = MetricKey("quota_memory_limit")
	QuotaMemoryRequest                    = MetricKey("quota_memory_request")
	RangeContainerCpu                     = MetricKey("range_container_cpu")
	RangeContainerMemory                  = MetricKey("range_container_memory")
	RangeContainerNetworkIO               = MetricKey("range_container_network_io")
	RangeContainerNetworkPacket           = MetricKey("range_container_network_packet")
	RangeDiskIO                           = MetricKey("range_disk_io")
	RangeFileSystem                       = MetricKey("range_file_system")
	RangeNetworkBandwidth                 = MetricKey("range_network_bandwidth")
	RangeNetworkPacketReceiveTransmit     = MetricKey("range_network_packet_receive_transmit")
	RangeNetworkPacketReceiveTransmitDrop = MetricKey("range_network_packet_receive_transmit_drop")
	RangeNodeCpu                          = MetricKey("range_node_cpu")
	RangeNodeCpuLoadAverage               = MetricKey("range_node_cpu_load_average")
	RangeNodeMemory                       = MetricKey("range_node_memory")
	RangeNodeNetworkIO                    = MetricKey("range_node_network_io")
	RangeNodeNetworkPacket                = MetricKey("range_node_network_packet")
	SummaryNodeInfo                       = MetricKey("summary_node_info")
)
